version: "3.8"

services:
  api:
    image: ghcr.io/madebaruna/paimon-moe-api:latest
    init: true
    restart: always
    ports:
      - "22000:3001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      XXHASH_SEED: ${XXHASH_SEED}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      REDIS_URL: ${REDIS_URL}
      TALLY_QUEUE_CONCURRENCY: ${TALLY_QUEUE_CONCURRENCY}
      PLAUSIBLE_URL: ${PLAUSIBLE_URL}
      PLAUSIBLE_TOKEN: ${PLAUSIBLE_TOKEN}
      HEADER_SECRET: ${HEADER_SECRET}
      PROXY_LOCATION: ${PROXY_LOCATION}
    volumes:
      - /home/baruna/server/service_account:/service_account
      - /home/baruna/server/proxies:/proxies

  postgres:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:6.2.4-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
